import { createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useChat } from "@ai-sdk/react";
import { DefaultChatTransport, type UIMessage } from "ai";
import { ArrowRight, BarChart3, Bot, Check, ChevronDown, Send, ShieldCheck, Sparkles } from "lucide-react";
import { useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import ReactMarkdown from "react-markdown";
import { Button } from "@/components/ui/button";
import { createDiagnostic, loadDiagnostic } from "@/lib/diagnostics.functions";
import logoAsset from "@/assets/charles-taylor-logo.png.asset.json";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "Claims & Fraud Intelligence | Charles Taylor" },
    { name: "description", content: "Evalúa la madurez de tu aseguradora en siniestros, fraude e IA con Charles Taylor." },
    { property: "og:title", content: "Claims & Fraud Intelligence | Charles Taylor" },
    { property: "og:description", content: "Diagnóstico ejecutivo de madurez en siniestros, fraude e inteligencia artificial." },
  ] }),
  component: Index,
});

type Profile = { name: string; company: string; email: string; role: string };
type Session = Profile & { id: string; visitorToken: string; messages: UIMessage[] };
const STORAGE_KEY = "ct-claims-diagnostic";
const roles = ["Director/a de Siniestros", "Director/a de Operaciones", "Director/a de Transformación", "Director/a de Innovación", "Director/a de Fraude", "CIO / CTO", "Responsable de Claims Excellence", "Responsable de Data / Analytics", "Otro"];

function Index() {
  const [session, setSession] = useState<Session | null>(null);
  const [restoring, setRestoring] = useState(true);
  const load = useServerFn(loadDiagnostic);
  useEffect(() => {
    const restore = async () => {
      try {
        const raw = window.localStorage.getItem(STORAGE_KEY);
        if (!raw) return;
        const saved = JSON.parse(raw) as { id: string; visitorToken: string };
        const row = await load({ data: saved });
        if (row) setSession({ ...saved, name: row.name, company: row.company, email: row.email, role: row.role, messages: row.messages as unknown as UIMessage[] });
      } catch { window.localStorage.removeItem(STORAGE_KEY); }
      finally { setRestoring(false); }
    };
    void restore();
  }, [load]);
  return <main className="min-h-screen overflow-hidden bg-background text-foreground"><Header/><Hero/><section id="diagnostico" className="relative bg-navy-soft px-5 py-20 md:px-10 md:py-28"><div className="pointer-events-none absolute inset-0 opacity-20 [background-image:radial-gradient(circle_at_20%_20%,var(--color-claims),transparent_32%),radial-gradient(circle_at_85%_80%,var(--color-insuretech),transparent_28%)]"/><div className="relative mx-auto max-w-6xl"><div className="mb-10 max-w-2xl text-primary-foreground"><p className="mb-4 text-xs font-bold uppercase tracking-[0.22em] text-primary">Diagnóstico inteligente</p><h2 className="font-display text-4xl font-bold leading-tight md:text-6xl">Convierte la complejidad en una hoja de ruta.</h2><p className="mt-5 max-w-xl text-sm leading-7 text-primary-foreground/65 md:text-base">Una conversación guiada de 15–20 minutos para identificar fricciones, riesgos y oportunidades reales de modernización.</p></div><div className="overflow-hidden rounded-2xl border border-primary-foreground/10 bg-card shadow-2xl shadow-foreground/20">{restoring ? <div className="flex h-[620px] items-center justify-center text-muted-foreground">Recuperando diagnóstico…</div> : session ? <DiagnosticChat key={session.id} session={session}/> : <StartDiagnostic onStarted={setSession}/>}</div></div></section><Capabilities/><Footer/></main>;
}

function Header() { return <header className="absolute inset-x-0 top-0 z-20 px-5 py-5 md:px-10"><nav className="mx-auto flex max-w-7xl items-center justify-between"><img src={logoAsset.url} alt="Charles Taylor" className="h-12 w-auto"/><a href="#diagnostico" className="hidden items-center gap-2 text-sm font-semibold text-primary-foreground md:flex">Iniciar diagnóstico <ArrowRight className="size-4"/></a></nav></header>; }
function Hero() { return <section className="relative flex min-h-[790px] items-end bg-navy-soft px-5 pb-20 pt-32 text-primary-foreground md:min-h-[850px] md:px-10 md:pb-28"><div className="absolute inset-0 overflow-hidden"><div className="absolute -right-40 top-20 h-[650px] w-[650px] rounded-full border border-primary-foreground/10"/><div className="absolute -right-12 top-52 h-[420px] w-[420px] rounded-full border border-primary/50"/><div className="absolute right-32 top-80 h-40 w-40 rounded-full bg-primary/90 blur-3xl"/><div className="absolute inset-y-0 right-[34%] w-px bg-gradient-to-b from-transparent via-primary-foreground/15 to-transparent"/></div><div className="relative mx-auto grid w-full max-w-7xl gap-14 md:grid-cols-[1.25fr_.75fr] md:items-end"><div><div className="mb-7 inline-flex items-center gap-2 rounded-full border border-primary-foreground/15 px-4 py-2 text-xs font-semibold uppercase tracking-[0.16em] text-primary-foreground/75"><Sparkles className="size-3.5 text-primary"/>Claims & Fraud Intelligence</div><h1 className="max-w-4xl font-display text-5xl font-bold leading-[0.96] tracking-[-0.04em] md:text-8xl">Decisiones más inteligentes.<br/><span className="text-primary">Siniestros más simples.</span></h1><p className="mt-8 max-w-2xl text-base leading-8 text-primary-foreground/65 md:text-lg">Descubre el nivel de madurez de tu operación de claims y fraude, y dónde la inteligencia aplicada puede generar impacto real.</p><Button asChild size="lg" className="mt-9 h-13 rounded-full px-7 font-bold"><a href="#diagnostico">Evaluar mi operación <ArrowRight/></a></Button></div><div className="border-l border-primary-foreground/15 pl-7"><p className="font-display text-6xl font-bold text-claims">15<span className="text-2xl">–20</span></p><p className="mt-1 text-sm font-semibold">minutos de conversación</p><div className="my-6 h-px bg-primary-foreground/10"/><p className="text-sm leading-6 text-primary-foreground/55">Un diagnóstico ejecutivo, modular y adaptado a la realidad de tu aseguradora.</p></div></div><a href="#diagnostico" aria-label="Bajar al diagnóstico" className="absolute bottom-6 left-1/2 -translate-x-1/2 text-primary-foreground/50"><ChevronDown/></a></section>; }

function StartDiagnostic({ onStarted }: { onStarted: (session: Session) => void }) {
  const [form, setForm] = useState<Profile>({ name: "", company: "", email: "", role: "" });
  const [error, setError] = useState(""); const [loading, setLoading] = useState(false); const create = useServerFn(createDiagnostic);
  const update = (key: keyof Profile, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(""); setLoading(true); try { const result = await create({ data: form }); const next = { ...form, ...result, messages: [] }; window.localStorage.setItem(STORAGE_KEY, JSON.stringify(result)); onStarted(next); } catch { setError("No hemos podido iniciar el diagnóstico. Inténtalo de nuevo."); } finally { setLoading(false); } };
  const inputClass = "mt-2 h-12 w-full rounded-lg border border-input bg-background px-4 text-sm normal-case outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/15";
  return <div className="grid min-h-[620px] md:grid-cols-[.85fr_1.15fr]"><div className="flex flex-col justify-between bg-muted p-8 md:p-12"><div><div className="mb-8 flex size-12 items-center justify-center rounded-xl bg-navy-soft text-primary"><Bot/></div><h3 className="font-display text-3xl font-bold text-navy-soft">Claims & Fraud<br/>Intelligence</h3><p className="mt-5 text-sm leading-7 text-muted-foreground">El agente analizará siete dimensiones de tu operación para construir una visión clara de tu madurez actual.</p></div><div className="mt-10 space-y-4 text-sm font-semibold text-navy-soft">{["Conversación consultiva", "Diagnóstico personalizado", "Recomendaciones modulares"].map((item) => <div key={item} className="flex items-center gap-3"><span className="flex size-6 items-center justify-center rounded-full bg-insurance/15 text-insurance"><Check className="size-3.5"/></span>{item}</div>)}</div></div><form onSubmit={submit} className="flex flex-col justify-center p-8 md:p-12"><p className="text-xs font-bold uppercase tracking-[0.2em] text-primary">Antes de empezar</p><h3 className="mt-3 font-display text-3xl font-bold text-navy-soft">Cuéntanos sobre ti.</h3><p className="mt-2 text-sm text-muted-foreground">Así podremos adaptar el diagnóstico a tu contexto.</p><div className="mt-8 grid gap-5 sm:grid-cols-2"><label className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Nombre<input required maxLength={120} value={form.name} onChange={(e) => update("name", e.target.value)} className={inputClass} placeholder="Tu nombre"/></label><label className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Compañía<input required maxLength={160} value={form.company} onChange={(e) => update("company", e.target.value)} className={inputClass} placeholder="Tu aseguradora"/></label><label className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Email corporativo<input required type="email" maxLength={254} value={form.email} onChange={(e) => update("email", e.target.value)} className={inputClass} placeholder="nombre@empresa.com"/></label><label className="text-xs font-bold uppercase tracking-wider text-muted-foreground">Rol<select required value={form.role} onChange={(e) => update("role", e.target.value)} className={inputClass}><option value="">Selecciona tu rol</option>{roles.map((role) => <option key={role}>{role}</option>)}</select></label></div>{error && <p className="mt-4 text-sm text-destructive">{error}</p>}<Button disabled={loading} size="lg" className="mt-7 h-12 w-full font-bold">{loading ? "Preparando diagnóstico…" : "Iniciar diagnóstico"}<ArrowRight/></Button><p className="mt-4 flex items-center justify-center gap-2 text-center text-[11px] text-muted-foreground"><ShieldCheck className="size-3.5"/>Tus respuestas se guardan de forma segura.</p></form></div>;
}

function DiagnosticChat({ session }: { session: Session }) {
  const [input, setInput] = useState(""); const textarea = useRef<HTMLTextAreaElement>(null); const end = useRef<HTMLDivElement>(null);
  const transport = useMemo(() => new DefaultChatTransport({ api: "/api/chat", body: { id: session.id, visitorToken: session.visitorToken } }), [session.id, session.visitorToken]);
  const { messages, sendMessage, status, error } = useChat({ id: session.id, messages: session.messages, transport }); const busy = status === "submitted" || status === "streaming";
  useEffect(() => { end.current?.scrollIntoView({ behavior: "smooth" }); }, [messages, status]); useEffect(() => { if (!busy) textarea.current?.focus(); }, [busy]);
  useEffect(() => { if (messages.length === 0) void sendMessage({ text: `Hola, me llamo ${session.name}, trabajo en ${session.company} como ${session.role}. Quiero realizar el diagnóstico.` }); }, [messages.length, sendMessage, session]);
  const submit = async (event: FormEvent) => { event.preventDefault(); const text = input.trim(); if (!text || text.length > 4_000 || busy) return; setInput(""); await sendMessage({ text }); textarea.current?.focus(); };
  return <div className="flex h-[700px] max-h-[85vh] flex-col bg-muted/40"><div className="flex items-center justify-between border-b bg-card px-5 py-4 md:px-7"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-full bg-navy-soft text-xs font-black text-primary">CT</span><div><p className="font-display text-sm font-bold text-navy-soft">Claims & Fraud Intelligence</p><p className="flex items-center gap-1.5 text-[11px] text-muted-foreground"><span className="size-1.5 rounded-full bg-insurance"/>Diagnóstico en curso</p></div></div><p className="hidden text-xs font-semibold text-muted-foreground sm:block">{session.company}</p></div><div className="flex-1 overflow-y-auto px-4 py-6 md:px-8"><div className="mx-auto flex max-w-3xl flex-col gap-5">{messages.map((message) => <div key={message.id} className={`flex gap-3 ${message.role === "user" ? "justify-end" : "justify-start"}`}>{message.role === "assistant" && <span className="flex size-8 shrink-0 items-center justify-center rounded-full bg-navy-soft text-[10px] font-black text-primary">CT</span>}<div className={`max-w-[82%] rounded-2xl px-4 py-3 text-sm leading-7 ${message.role === "user" ? "rounded-tr-sm bg-navy-soft text-primary-foreground" : "rounded-tl-sm border bg-card text-card-foreground"}`}>{message.parts.map((part, index) => part.type === "text" ? <div key={index} className="prose prose-sm max-w-none prose-p:my-1 prose-ul:my-2"><ReactMarkdown>{part.text}</ReactMarkdown></div> : null)}</div></div>)}{status === "submitted" && <div className="flex items-center gap-3"><span className="flex size-8 items-center justify-center rounded-full bg-navy-soft text-[10px] font-black text-primary">CT</span><div className="flex gap-1 rounded-2xl border bg-card px-5 py-4">{[0,1,2].map((n) => <span key={n} className="size-1.5 rounded-full bg-muted-foreground [animation:agent-pulse_1s_infinite]" style={{ animationDelay: `${n * 140}ms` }}/>)}</div></div>}<div ref={end}/></div></div><form onSubmit={submit} className="border-t bg-card p-4 md:px-7"><div className="mx-auto flex max-w-3xl items-end gap-3"><textarea ref={textarea} autoFocus rows={2} maxLength={4_000} value={input} onChange={(e) => setInput(e.target.value)} onKeyDown={(e) => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); e.currentTarget.form?.requestSubmit(); } }} placeholder="Escribe tu respuesta…" className="min-h-12 flex-1 resize-none rounded-xl border border-input bg-background px-4 py-3 text-sm outline-none focus:border-primary focus:ring-2 focus:ring-primary/15"/><Button type="submit" size="icon" disabled={!input.trim() || input.length > 4_000 || busy} className="size-12 rounded-xl"><Send/></Button></div>{error && <p className="mx-auto mt-2 max-w-3xl text-xs text-destructive">No hemos podido obtener respuesta. Revisa tu conexión e inténtalo de nuevo.</p>}</form></div>;
}

function Capabilities() { const items = [{ icon: BarChart3, tag: "01", title: "Claims intelligence", text: "Convierte datos operativos dispersos en señales claras para priorizar, anticipar y decidir." }, { icon: ShieldCheck, tag: "02", title: "Fraude conectado", text: "Combina reglas, patrones y contexto para detectar riesgo con menos fricción y falsos positivos." }, { icon: Bot, tag: "03", title: "IA gobernada", text: "Activa casos de uso concretos, auditables y alineados con tus procesos y sistemas actuales." }]; return <section className="px-5 py-20 md:px-10 md:py-28"><div className="mx-auto max-w-7xl"><div className="grid gap-8 border-b pb-12 md:grid-cols-2"><h2 className="font-display text-4xl font-bold leading-tight text-navy-soft md:text-6xl">Inteligencia aplicada.<br/>Impacto tangible.</h2><p className="max-w-lg self-end text-sm leading-7 text-muted-foreground md:justify-self-end">Modernización modular para mejorar la eficiencia, reducir el riesgo y elevar la experiencia sin transformar todo desde cero.</p></div><div className="grid md:grid-cols-3">{items.map(({ icon: Icon, tag, title, text }, index) => <article key={title} className={`py-10 md:px-9 ${index > 0 ? "border-t md:border-l md:border-t-0" : ""}`}><div className="flex items-center justify-between"><Icon className="size-7 text-primary"/><span className="font-mono text-xs text-muted-foreground">{tag}</span></div><h3 className="mt-12 font-display text-2xl font-bold text-navy-soft">{title}</h3><p className="mt-4 text-sm leading-7 text-muted-foreground">{text}</p></article>)}</div></div></section>; }
function Footer() { return <footer className="bg-navy-soft px-5 py-8 text-primary-foreground md:px-10"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-5 md:flex-row"><img src={logoAsset.url} alt="Charles Taylor" className="h-10 w-auto rounded-sm"/><p className="text-xs text-primary-foreground/45">Claims & Fraud Intelligence · Soluciones modulares para aseguradoras</p></div></footer>; }
